name: Daily Reminder
on:
  schedule:
    - cron: "0 9 * * *" 
  workflow_dispatch:
  
jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run reminder
        uses: ./